**__pycache__**
**/*.pyc
**.cache**
**/*.ipynb_checkpoints*
**/*.DS_store*
quetzal/.git
quetzal/.venv
quetzal/wheels-cp38-win_amd64
quetzal/docker/infra
quetzal_cyclops/.git/lfs
quetzal_cyclops/.git/objects
quetzal_cyclops/scenarios/*

